sudo: required
dist: trusty
addons:
  apt:
    sources:
      - xvfb
      - firefox
language: node_js
node_js:
  - "6"
install:
  - Xvfb :19 -screen 0 1024x768x16
  - export DISPLAY=:19
script:
  - npm test
